// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJT1YL71hx2xEHQkxYegQ3BGHAMjfBLCI',
    appId: '1:19864496146:android:c8e82a8feae10e0daf50cb',
    messagingSenderId: '19864496146',
    projectId: 'authentication-3966e',
    storageBucket: 'authentication-3966e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBWqr-H-rYDUSBPTNl_BkQDr1WZer_KxI',
    appId: '1:19864496146:ios:b0f3ab092f0f292aaf50cb',
    messagingSenderId: '19864496146',
    projectId: 'authentication-3966e',
    storageBucket: 'authentication-3966e.appspot.com',
    iosBundleId: 'com.example.authenticationproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBWqr-H-rYDUSBPTNl_BkQDr1WZer_KxI',
    appId: '1:19864496146:ios:28ad2f7a2f2a032eaf50cb',
    messagingSenderId: '19864496146',
    projectId: 'authentication-3966e',
    storageBucket: 'authentication-3966e.appspot.com',
    iosBundleId: 'com.example.authenticationproject.RunnerTests',
  );
}
